config/routes.rb
Rails.application.routes.draw do
  root'pages#home'
  get'pages/about' => 'pages#about'

  resources :articles

  get 'signup' => 'users#new'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users, except: [:new]
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence:true,length: {minimum: 3, maximum:50}
  validates :description, presence:true, length: {minimum: 10, maximum:1000}
  validates :user_id, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, :dependent => :destroy
  has_secure_password
  before_save {self.email = email.downcase }
  validates :username, presence: true,
  uniqueness: {case_sensitive: false},
  length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true,
  uniqueness: {case_sensitive: false},
  length: {maximum: 100},
  format: {with: VALID_EMAIL_REGEX}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  ##controllerでのみ使える。viewでも使えるようにするためにhelper_methodを利用する
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:edit,:update,:destroy]
  before_action :require_user, except: [:index,:show]


  def index
    @articles = Article.paginate(page: params[:page],per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:success] = "Article was successfully created"
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end

  def show
  end

  def destroy
    @article.destroy
    flash[:danger] = "Article was successfully deleted."
    redirect_to articles_path
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated."
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end



  private
  def article_params
    params.require(:article).permit(:title,:description)
  end

  def set_article
    @article = Article.find(params[:id])
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in!!"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new,:create,:index]
  before_action :require_same_user, only: [:edit,:update]
  before_action :require_admin, only: [:destroy]


  def index
    @users = User.paginate(page:params[:page],per_page:5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    session[:user_id] = @user.id
    if @user.save
      flash[:success] = "Welcome to the blank blog #{@user.username}!"
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully!"
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user_articles = @user.articles.paginate(page:params[:page],per_page:5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted."
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:danger] = "You can only edit and delete your own articles"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? && !current_user.admin?
      flash[:danger] = "Only Admin can perform this action."
      redirect_to root_path
    end
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, option ={size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = option[:size]
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt:user.username,class:"img-circle")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.haml
-obj.each do |article|
  .row
    .col-xs-8.col-xs-offset-2
      .well.well-lg
        .article-title
          =link_to "#{article.title}",article_path(article)
        .article-body
          =truncate(article.description,length:150)
        -if logged_in? && (current_user == article.user || current_user.admin?)
          .article-actions.right
            =link_to "Edit",edit_article_path(article),{class: "btn btn-primary"}
            =link_to "Delete",article_path(article),{class: "btn btn-danger ", method: :delete}

app/views/articles/_form.html.haml
=render 'shared/errors', obj: @article

.row
  .col-xs-12
    =form_for @article, html: {class: "form-horizontal",role:"form"} do |f|
      .form-group
        .control-label.col-sm-2
          =f.label :title
        .col-sm-8
          =f.text_field :title, class: "form-control",placeholder: "Title of Article", autofocus: true
      .form-group
        .control-label.col-sm-2
          =f.label :description
        .col-sm-8
          =f.text_area :description, rows: "10", class: "form-control",placeholder: "Body of Article", autofocus: true
      .form-group
        .col-sm-offset-2.col-sm-10
          =f.submit class:"btn btn-primary btn-lg"

app/views/articles/edit.html.haml
.main
  %h1.add-border-bottom Edit existing articles
  =render 'form'

app/views/articles/index.html.haml
.main
  %h1.add-border-bottom List of Artcles
  .center
    =will_paginate
  =render 'article',obj:@articles
  .center
    =will_paginate






  / .info=link_to "Create new",new_article_path
  / .panel.panel-default
  /   .panel-heading Articles
  /   %table.table
  /     %tr
  /       %th.add-bold Title
  /       %th.add-bold Description
  /     -@articles.each do |article|
  /       %tr
  /         %td= article.title
  /         %td= article.description.truncate(60)
  /         %td=link_to 'Edit',edit_article_path(article)
  /         %td=link_to 'Show',article_path(article)
  /         %td=link_to 'Delete',article_path(article),method: :delete,data: {confirm: "Are you sure?"}

app/views/articles/new.html.haml
.main
  %h1.add-border-bottom Create an article
  =render 'form'

app/views/articles/show.html.haml
.show
  %h1#add-space.add-border-bottom= "Title: #{@article.title}"
  %h2.subtitle Description:
  %p.description-style=@article.description
  -if logged_in? && (current_user == @article.user || current_user.admin?)
    .article-actions.right
    =link_to "Edit",edit_article_path(@article),{class: "btn btn-primary"}
    =link_to "Delete",article_path(@article),{class: "btn btn-danger ", method: :delete}

app/views/layouts/_footer.html.haml
.main
  .footer.footer.add-border.center
    %small
      Copyright &copy
      =link_to "The blank blog Developer","#"
      by
      =link_to "Brown Hash","#"

app/views/layouts/_messages.html.haml
.row
  .col-xs-10.col-xs-offset-1
    -flash.each do|name,msg|
      %div{class: "alert alert-#{name}"}= msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      =link_to"blank blog",root_path,{class: "navbar-brand logo"}
    .nav.navbar-nav
      %li=link_to "Articles",articles_path
      %li=link_to "Users",users_path
      %li.dropdown
        %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Actions
          %span.caret
        %ul.dropdown-menu
          %li
            =link_to"New Article",new_article_path
          %li
            %a{:href => "#"} Another action
    .nav.navbar-nav.navbar-right
      -if logged_in?
        %li=link_to"LOG OUT",logout_path,method: :delete
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Your Profile
            %span.caret
          %ul.dropdown-menu
            %li
              =link_to"Edit your profile",edit_user_path(current_user)
              =link_to"View your profile",user_path(current_user)
            %li
              %a{:href => "#"} Another action
      -else
        %li=link_to"LOG IN",login_path
        %li=link_to"SIGN IN",signup_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlankBlog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    = render 'layouts/messages'
    = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?

app/views/pages/about.html.haml
%h1 About What???

app/views/pages/home.html.haml
.main
  .jumbotron.center.add-background-image
    %h1.add-space BLANK BLOG
    =link_to "Sign up now",signup_path,{class: "btn btn-primary btn-lg"}

app/views/shared/_errors.html.haml
-if obj.errors.any?
  .row
    .col-xs-8.col-xs-offset-2
      .panel.panel-danger
        .panel-heading
          %h2.panel-title
            =pluralize(obj.errors.count, "error")
            prohibited this article from being saved:
          .panel-body
            %ul
              -obj.errors.full_messages.each do |msg|
                %li
                  =msg

app/views/users/_form.html.haml
.row
  .col-xs-12
    =form_for @user, html: {class: "form-horizontal",role:"form"} do |f|
      .form-group
        .control-label.col-sm-2
          =f.label :username
        .col-sm-8
          =f.text_field :username, class: "form-control",placeholder: "Enter your name", autofocus: true
      .form-group
        .control-label.col-sm-2
          =f.label :email
        .col-sm-8
          =f.email_field :email, rows: "1", class: "form-control",placeholder: "Enter your email", autofocus: true
      .form-group
        .control-label.col-sm-2
          =f.label :password
        .col-sm-8
          =f.password_field :password, rows: "1", class: "form-control",placeholder: "Enter your password", autofocus: true
      .form-group
        .col-sm-offset-2.col-sm-10
          =f.submit(@user.new_record? ? "Sign up": "Update account" , class:"btn btn-primary btn-lg")

app/views/users/edit.html.haml
.main
  =render 'shared/errors', obj: @user
  %h1.add-border-bottom.center Update your profile
  =render 'form'

app/views/users/index.html.haml
%div.center
  %h1 All Blank-Blog Bloggers
  =will_paginate
  -@users.each do |user|
    %ul.listing
      .row
        .well.col-md-4.col-md-offset-4
          %li=link_to gravatar_for(user),user_path(user)
          %li.article-title
            =link_to user.username, user_path(user)
          %li=pluralize(user.articles.count, "article") if user.articles
          -if logged_in? && current_user.admin?
            %li=link_to "Delete this user",user_path(user),method: :delete,data: {confirm: "Are you sure you want to delete the and all articles?  "}
  =will_paginate

app/views/users/new.html.haml
.main
  =render 'shared/errors', obj: @user
  %h1.add-border-bottom.center Signup for blank blog
  .row
    .col-xs-12
      =form_for @user, html: {class: "form-horizontal",role:"form"} do |f|
        .form-group
          .control-label.col-sm-2
            =f.label :username
          .col-sm-8
            =f.text_field :username, class: "form-control",placeholder: "Enter your name", autofocus: true
        .form-group
          .control-label.col-sm-2
            =f.label :email
          .col-sm-8
            =f.email_field :email, rows: "1", class: "form-control",placeholder: "Enter your email", autofocus: true
        .form-group
          .control-label.col-sm-2
            =f.label :password
          .col-sm-8
            =f.password_field :email, rows: "1", class: "form-control",placeholder: "Enter your password", autofocus: true
        .form-group
          .col-sm-offset-2.col-sm-10
            =f.submit "Signup", class:"btn btn-primary btn-lg"

app/views/users/show.html.haml
%h1.center.add-top-margin= "Welcome to #{@user.username}'s page"
.row.add-top-space
  %ul.listing
  .row.center
    .col-md-4.col-md-offset-4
      %li=link_to gravatar_for(@user),user_path(@user)
      %li.article-title
        =link_to @user.username, user_path(@user)
      %li=pluralize(@user.articles.count, "article") if @user.articles
  .center
    =will_paginate @user_articles
  =render 'articles/article',obj: @user.articles